name: polymer_core_and_paper_examples
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: Polymer core and paper elements examples for Dart
homepage: https://www.dartlang.org/polymer/
dependencies:
  polymer: ">=0.15.2 <0.17.0"
  core_elements: ">=0.7.0 <0.8.0"
  paper_elements: ">=0.7.0 <0.8.0"
environment:
  sdk: '>=1.6.0 <2.0.0'
transformers:
- polymer:
    entry_points:
    inline_stylesheets:
      lib/src/paper-shadow/paper-shadow.css: false
- $dart2js:
    $include: "**/*.polymer.bootstrap.dart"
