name: polymer_core_and_paper_examples
version: 0.1.0
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: Polymer core and paper elements examples for Dart
homepage: https://www.dartlang.org/polymer/
dependencies:
  polymer: ">=0.15.2 <0.16.0"
  core_elements: ">=0.5.0 <0.6.0"
  paper_elements: ">=0.6.0 <0.7.0"
dev_dependencies:
  path: ">=1.3.0 <1.4.0"
environment:
  sdk: '>=1.6.0 <2.0.0'
transformers:
- polymer:
    entry_points:
    inline_stylesheets:
      lib/src/paper-shadow/paper-shadow.css: false
